---
title: "Divewatchr Dataset Overview"
output: html_document
---
  

```{r include = FALSE}
devtools::install_github("rubenpp7/divewatchr")
library(divewatchr)
```

```{r echo = FALSE}
setwd("C:/Users/rubenp/Desktop/Huiswerk 2020/Logbook Scuba Ruben Perez/divewatchr")
load('data/scuba_map.RData')
load('data/scuba_clean.RData')
logbook_map()
```

```{r echo = FALSE}
setwd("C:/Users/rubenp/Desktop/Huiswerk 2020/Logbook Scuba Ruben Perez/divewatchr")
load('data/scuba_map.RData')
logged_depths()
```

```{r echo = FALSE}
setwd("C:/Users/rubenp/Desktop/Huiswerk 2020/Logbook Scuba Ruben Perez/divewatchr")
load('data/scuba_clean.RData')
load('data/scuba_map.RData')
cum_dives()
```

```{r echo = FALSE}
setwd("C:/Users/rubenp/Desktop/Huiswerk 2020/Logbook Scuba Ruben Perez/divewatchr")
load('data/scuba_clean.RData')
divetypes()
```

```{r echo = FALSE}
setwd("C:/Users/rubenp/Desktop/Huiswerk 2020/Logbook Scuba Ruben Perez/divewatchr")
load('data/scuba_clean.RData')
divecount_reg()
```

```{r echo = FALSE}
setwd("C:/Users/rubenp/Desktop/Huiswerk 2020/Logbook Scuba Ruben Perez/divewatchr")
load('data/scuba_map.RData')
divesite_depths()
```

```{r echo = FALSE}
setwd("C:/Users/rubenp/Desktop/Huiswerk 2020/Logbook Scuba Ruben Perez/divewatchr")
load('data/scuba_clean.RData')
divetypes_platform()
```
